name: kursor-microservices

services:
  api-gateway:
    build:
      dockerfile: api-gateway/Dockerfile
context: .
    environment:
      PORT: 3000
EXECUTION_SERVICE_URL: ${{execution-service.RAILWAY_PRIVATE_DOMAIN}}:3001
COMMUNICATION_SERVICE_URL: ${{communication-service.RAILWAY_PRIVATE_DOMAIN}}:3002
SNIPPET_SERVICE_URL: ${{snippet-service.RAILWAY_PRIVATE_DOMAIN}}:3003
USER_SERVICE_URL: ${{user-service.RAILWAY_PRIVATE_DOMAIN}}:3004
healthcheck:
      path: /health
interval: 30s
timeout: 5s
retries: 3

execution-service:
    build:
      dockerfile: services/execution-service/Dockerfile
context: .
    environment:
      PORT: 3001
RAPIDAPI_KEY: ${{RAPIDAPI_KEY}}
RAPIDAPI_HOST: judge0-ce.p.rapidapi.com
healthcheck:
      path: /health
interval: 30s
timeout: 5s
retries: 3

communication-service:
    build:
      dockerfile: services/communication-service/Dockerfile
context: .
    environment:
      PORT: 3002
RESEND_API_KEY: ${{RESEND_API_KEY}}
ADMIN_EMAIL: ${{ADMIN_EMAIL}}
healthcheck:
      path: /health
interval: 30s
timeout: 5s
retries: 3

snippet-service:
    build:
      dockerfile: services/snippet-service/Dockerfile
context: .
    environment:
      PORT: 3003
DATABASE_URL: ${{DATABASE_URL}}
healthcheck:
      path: /health
interval: 30s
timeout: 5s
retries: 3

user-service:
    build:
      dockerfile: services/user-service/Dockerfile
context: .
    environment:
      PORT: 3004
DATABASE_URL: ${{DATABASE_URL}}
JWT_SECRET: ${{JWT_SECRET}}
healthcheck:
      path: /health
interval: 30s
timeout: 5s
retries: 3
# Railway deployment configuration
